/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyScopedComponent {
        /**
          * @default false
         */
        "visible": boolean;
    }
    interface MyShadowComponent {
        /**
          * @default false
         */
        "visible": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyScopedComponentElement extends Components.MyScopedComponent, HTMLStencilElement {
    }
    var HTMLMyScopedComponentElement: {
        prototype: HTMLMyScopedComponentElement;
        new (): HTMLMyScopedComponentElement;
    };
    interface HTMLMyShadowComponentElement extends Components.MyShadowComponent, HTMLStencilElement {
    }
    var HTMLMyShadowComponentElement: {
        prototype: HTMLMyShadowComponentElement;
        new (): HTMLMyShadowComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-scoped-component": HTMLMyScopedComponentElement;
        "my-shadow-component": HTMLMyShadowComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyScopedComponent {
        /**
          * @default false
         */
        "visible"?: boolean;
    }
    interface MyShadowComponent {
        /**
          * @default false
         */
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-scoped-component": MyScopedComponent;
        "my-shadow-component": MyShadowComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-scoped-component": LocalJSX.MyScopedComponent & JSXBase.HTMLAttributes<HTMLMyScopedComponentElement>;
            "my-shadow-component": LocalJSX.MyShadowComponent & JSXBase.HTMLAttributes<HTMLMyShadowComponentElement>;
        }
    }
}
