/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppProfile {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyGlobalCounter {
    }
}
declare global {
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyGlobalCounterElement extends Components.MyGlobalCounter, HTMLStencilElement {
    }
    var HTMLMyGlobalCounterElement: {
        prototype: HTMLMyGlobalCounterElement;
        new (): HTMLMyGlobalCounterElement;
    };
    interface HTMLElementTagNameMap {
        "app-profile": HTMLAppProfileElement;
        "my-component": HTMLMyComponentElement;
        "my-global-counter": HTMLMyGlobalCounterElement;
    }
}
declare namespace LocalJSX {
    interface AppProfile {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyGlobalCounter {
    }
    interface IntrinsicElements {
        "app-profile": AppProfile;
        "my-component": MyComponent;
        "my-global-counter": MyGlobalCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-global-counter": LocalJSX.MyGlobalCounter & JSXBase.HTMLAttributes<HTMLMyGlobalCounterElement>;
        }
    }
}
